# Generated by Django 4.2.2 on 2023-07-08 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_until',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 21, 4, 16, 62489, tzinfo=datetime.timezone.utc)),
        ),
    ]
