# Generated by Django 4.2.2 on 2023-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_until',
            field=models.DateField(default=None, null=True),
        ),
    ]
