# Generated by Django 4.2.3 on 2023-07-06 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(default=datetime.datetime(2023, 7, 10, 17, 48, 34, 23122, tzinfo=datetime.timezone.utc))),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copies.copy')),
            ],
        ),
    ]
