# Generated by Django 4.2.3 on 2023-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='data_devolucao',
            field=models.DateField(),
        ),
    ]
