# Generated by Django 4.2.2 on 2023-07-08 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_data_devolucao_alter_loan_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 20, 45, 41, 500749, tzinfo=datetime.timezone.utc)),
        ),
    ]
