# Generated by Django 4.2.2 on 2023-07-08 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 21, 23, 27, 909177, tzinfo=datetime.timezone.utc)),
        ),
    ]
